name: DEV DEPLOYMENT

on:
  push:
    branches: ["dev"]

jobs:
  build:
    runs-on:
      - self-hosted
      - dev
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.17.0
      - name: Install Dependencies
        run: yarn
      - name: Build PWA
        run: npx quasar build -m pwa
      - name: Move Build Files to Directory
        run: cp -R dist/pwa /var/www/amt-clone/amt-viol/dist/
