name: DEV DEPLOYMENT

on:
  push:
    branches: ["dev"]

jobs:
  build:
    runs-on:
      - self-hosted
      - dev
    steps:
      - uses: actions/checkout@v3
      - name: Create .env file from variable
        run: echo "${{ vars.DEV_ENV }}" > .env
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.19.0
      - name: Install Dependencies
        run: yarn
      - name: Build PWA
        run: npx quasar build -m pwa
      - name: Move Build Files to Directory
        run: cp -R dist/pwa ${{ secrets.DEV_DEPLOY_PATH }}
